### ISSUE TITLE
Session remains every fmt error with tmux 

### ISSUE THREAD

**Issue by bigwheel** [matheusq94/terraform-format-on-save#1]
It seems every fmt error creates tmux session and doesn't destroy it.

https://gist.github.com/bigwheel/100e12e9f217802175262f62561b87f6

Finally, tmux CPU usage consumes large CPU time.

**Comment by charltonstanley** [comment]
similar experience, but for me it ate through all the ram on my computer.

**Comment by Gabryel8818** [comment]
@charltonstanley and @bigwheel hello peoples

I have created a code in this [PR ](https://github.com/matheusq94/terraform-format-on-save/pull/4)  
where the problem seems to have been resolved, can you check?

**Comment by bigwheel** [comment]
@Gabryel8818 
10 minutes ago I re-installed (pic 1) and still occured (pic2).
![image](https://github.com/matheusq94/terraform-format-on-save/assets/826646/cbb3ad96-b500-424c-ab91-666cd9216266)
![image](https://github.com/matheusq94/terraform-format-on-save/assets/826646/29d2eda9-b62f-4a12-b55d-419a9a5ac200)
